<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <UseWPF>true</UseWPF>

    <RootNamespace>Stealth</RootNamespace>
    <AssemblyName>Stealth</AssemblyName>
    <ApplicationIcon>Stealth.ico</ApplicationIcon>

    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <AssemblyTitle>Stealth</AssemblyTitle>
    <AssemblyDescription></AssemblyDescription>
    <AssemblyCompany></AssemblyCompany>
    <AssemblyProduct>Stealth</AssemblyProduct>
    <AssemblyCopyright>Copyright ©  2026</AssemblyCopyright>
    <AssemblyVersion>0.7.0</AssemblyVersion>
    <FileVersion>0.7.0</FileVersion>
    <ComVisible>false</ComVisible>

    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>

    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Platforms>AnyCPU</Platforms>
    <Prefer32Bit>false</Prefer32Bit>
    <WarningLevel>4</WarningLevel>
    <LangVersion>preview</LangVersion>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|AnyCPU'">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <DefineConstants>TRACE</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommonServiceLocator" Version="2.0.7" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Windows.CsWin32" Version="0.3.335" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="NativeMethods.txt" />
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <Resource Include="Stealth.ico" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>

    <Compile Update="Properties\Resources.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>

    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>

    <Compile Update="Properties\Settings.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>